apiVersion: v1
kind: Service
metadata:
  name: $appName
  namespace: $nameSpace
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: $appName
